add info about DockerHub and tags of images
JetBrains/projector-docker pull request #13
Opened 2021-10-14 11:26 UTC by Avvessalom

Add info about our DockerHub

2021-10-14 17:37 UTC, SerVB commented
Oleg, could you please review first please? And I will review after you.

2021-11-25 20:32 UTC, SerVB commented
Please request my review before merging. For now I'm going out of this PR to clean the list of pending PRs a bit :)

2021-12-06 11:17 UTC, olegchir approved these changes
Too many grammatical errors. Do you have MSWord or https://languagetool.org/, or any other checker? Also, the text can be much more informative

2021-12-10 17:02 UTC, Avvessalom commented
Yes, I have “language tools” and “Grammarly”. Both of these text checkers do not see grammar errors. Could you please point out grammatical errors so that I can correct them?

> Also, the text can be much more informative

This is just new information about versioning our images. What information would you like to see here more?

2022-02-02 11:27 UTC, olegchir approved these changes
Nice to have at least something :)

I think that all these texts should be checked by someone from JB Proofreading Team. But that's another story.

2022-02-02 11:28 UTC, cqupt-zjs commented
您好，俺已经收到了恁里邮件，谢谢哈~

2022-02-02 18:08 UTC, SerVB requested changes
This can be improved in terms of formatting, grammar, and user-friendliness.

2022-02-02 18:08 UTC, SerVB commented on README.md
> +docker pull jetbrains/projector-datagrip:latest
Two proposals:
1. Isn't `:latest` redundant?
2. Let's sort the list (like the Space list; it should be more user-friendly).

2022-02-02 18:08 UTC, SerVB commented on README.md
> +from Space:
For now, I find formatting here a bit difficult to understand. Maybe we can add points to make it more clear, like the following:
```suggestion
#### **Option A**. From Space:
```

2022-02-02 18:08 UTC, SerVB commented on README.md
> +or from [DockerHub](https://hub.docker.com/orgs/jetbrains/repositories):
```suggestion
#### **Option B**. From [DockerHub](https://hub.docker.com/orgs/jetbrains/repositories):
```

2022-02-02 18:08 UTC, SerVB commented on README.md
> +Firstly, pull an image with needed IDE
```suggestion
### Step 1

Firstly, pull an image with the needed IDE:
```

2022-02-02 18:08 UTC, SerVB commented on README.md
> +on space published only latest tested IDE and develop version of projector,
```suggestion
On Space, only the latest tested IDE and the `develop` version of Projector are published.
```

2022-02-02 18:08 UTC, SerVB commented on README.md
> +
```suggestion

### Step 2
```

2022-02-02 18:08 UTC, SerVB commented on README.md
> + - `<IDE_VERSION>-projector-<PROJECTOR_VERSION>` This image contains the selected version of IDE with the selected stable version of Projector.
```suggestion
 - `:latest` – this image contains the **latest up-to-date** version of the tested IDE with the latest **stable** version of the Projector.
 - `:develop` – this image contains the **latest up-to-date** version of the tested IDE with the **latest commit** of the Projector repository.
 - `:<IDE_VERSION>-develop` – this image contains the **selected** version of the IDE with the **latest commit** of the Projector repository. 
 - `<IDE_VERSION>-projector-<PROJECTOR_VERSION>` – this image contains the **selected** version of the IDE with the **selected stable** version of Projector.
```

2022-02-02 18:08 UTC, SerVB commented on README.md
> +on space published only latest tested IDE and develop version of projector,
By the way, at this point, the reader doesn't know yet what is `develop`. Maybe swapping these two options (Space and Docker Hub)?

2022-02-02 18:08 UTC, SerVB commented on README.md
> + - `<IDE_VERSION>-projector-<PROJECTOR_VERSION>` This image contains the selected version of IDE with the selected stable version of Projector.
Maybe a table will be better here, you can try to check it if you want

2022-02-03 08:28 UTC, Avvessalom commented on README.md
> +from Space:
Good note. Indeed, it doesn't seem very clear when looking at it for the first time. I found an elegant solution. It also slightly changes the structure of the image description to a more understandable one.

2022-02-10 10:53 UTC, SerVB approved these changes
LGTM, but a couple of minor suggestions

2022-02-10 10:53 UTC, SerVB commented on README.md
> +- `<IDE_VERSION>-projector-<PROJECTOR_VERSION>` – this image contains the **selected** version of the IDE with the **selected stable** version of Projector.
Just noticed this little guy missing :)

```suggestion
- `:<IDE_VERSION>-projector-<PROJECTOR_VERSION>` – this image contains the **selected** version of the IDE with the **selected stable** version of Projector.
```

2022-02-10 10:53 UTC, SerVB commented on README.md
>  example, `registry.jetbrains.team/p/prj/containers/projector-clion`):
Just reread the readme and see that the text here can be simplified a bit:

```suggestion
example, `jetbrains/projector-clion`):
```

2022-02-10 12:16 UTC, Avvessalom commented on README.md
>  example, `registry.jetbrains.team/p/prj/containers/projector-clion`):
in the original README the path to our Space repository.
ok, I will replace Space with DockerHub

2022-02-17 14:24 UTC, merged