PRJ-584 Add additional software related to specific IDE
JetBrains/projector-docker pull request #16
Opened 2021-11-21 01:01 UTC by nitrotol

Resolving [PRJ-584](https://youtrack.jetbrains.com/issue/PRJ-584)

Also, maybe, we need to add more software to specific IDEs

2021-11-21 01:07 UTC, nitrotol commented
Solution tested with CLion and Rider

2021-11-22 10:36 UTC, SerVB requested changes
Cool changes, make the script a bit cleaner I would say. However, the code can be improved.

2021-11-22 10:36 UTC, SerVB commented on Dockerfile
> -   && set -x \
It was handy to see the commands, so I suggest to leave these `set`s.

2021-11-22 10:36 UTC, SerVB commented on Dockerfile
> +RUN rm /install-additional-software.sh && rm -rf /var/lib/apt/lists/* && rm -rf /var/cache/apt
This should be done in the same `RUN` where `apt` is run since every `RUN` creates its own layer. If we clean something in a separate `RUN`, it won't reduce the size of the resulting image.

2021-11-22 10:36 UTC, SerVB commented on build-tools/install-additional-software.sh
> +    SOFTWARE_LIST=$(sed -z 's/  */ /g;s/\n//g' <<- EOM
Interesting script. However, there is a lot of duplicated code. Can we somehow extract duplicated code to a function or to a constant? I mean this part: `sed -z 's/ */ /g;s/\n//g'` or maybe even including `EOM`...

2021-11-22 11:15 UTC, nitrotol commented on Dockerfile
> +RUN rm /install-additional-software.sh && rm -rf /var/lib/apt/lists/* && rm -rf /var/cache/apt
Ok. I think this is not a problem to add this to each `RUN` with `apt`

2021-11-22 11:17 UTC, nitrotol commented on build-tools/install-additional-software.sh
> +    SOFTWARE_LIST=$(sed -z 's/  */ /g;s/\n//g' <<- EOM
I also think about it. But this is just a PoC and I dont be sure that my idea will be approved. I can move `sed ...` block to constant, but `EOM` is a part of heredoc string definition, so I cant move it

2021-11-22 11:18 UTC, nitrotol commented
@SerVB thanks for you comments! I add this changes a little bit later today

2022-05-26 11:50 UTC, error0x001 commented
Hello there! What about the PR? I really want to use my browser as IDE, but cannot at the moment.

2022-05-26 11:50 UTC, cqupt-zjs commented
您好，俺已经收到了恁里邮件，谢谢哈~

2022-07-15 12:50 UTC, yole commented
We're discontinuing the development of projector-docker and no longer accepting contributions, sorry.

2022-07-15 12:50 UTC, closed without merging